service: fizzy
image: very-normal/repository-2/fizzy

servers:
  web:
    - 34.63.167.166

ssh:
  user: jesse

proxy:
  ssl: true
  host: fizzy.verynormal.dev

env:
  secret:
    - SECRET_KEY_BASE
    - VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY
    - SMTP_USERNAME
    - SMTP_PASSWORD
  clear:
    BASE_URL: https://fizzy.verynormal.dev
    MAILER_FROM_ADDRESS: fizzy@verynormal.dev
    SMTP_ADDRESS: smtp.resend.com
    MULTI_TENANT: false
    SOLID_QUEUE_IN_PUMA: true

registry:
  server: us-docker.pkg.dev
  username: oauth2accesstoken
  password:
    - KAMAL_REGISTRY_PASSWORD

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "fizzy_storage:/rails/storage"

asset_path: /rails/public/assets

logging:
  driver: gcplogs
  options:
    gcp-project: very-normal

builder:
  arch: amd64
  remote: ssh://jesse@34.63.167.166
